version: '3'
services:

  dotnet-app:
    container_name: dotnet-app
    build: .
    ports:
      - 8080:80
      - 4443:443
    depends_on:
      - caddy

  caddy:
    container_name: caddy
    build: ./caddy/
    #domainname: dotnetdom
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/file:/etc/caddy
      - ./caddy/data:/data
      #- cdata:/data
      #- cfile:/etc/caddy

# volumes:
#   cdata:
#   cfile: